
### Products
// @no-log
// @no-auto-encoding
GET http://localhost:9962/product/?select(id,name,totalPrice,reviews)

### Create Product 1
// @no-log
POST http://localhost:9962/product/
Content-Type: application/json

{
  "id": "p1",
  "name": "Aurora Smart Lamp",
  "readyForMarket": true,
  "released": "2024-05-12",
  "thumbnail": "aHVtYW5fcmVhZGFibGVfdGh1bWJuYWlsX2J5dGVz",
  "image": "aHVtYW5fcmVhZGFibGVfaW1hZ2VfYmxvYg==",
  "quantity": 250,
  "desiredSaleQuantity": 5000,
  "price": 79.99,
  "taxRate": 0.07,
  "realTaxRate": 70000000000000000,
  "metadata": {
    "category": "Smart Home",
    "color": "Matte Black",
    "dimensions": {
      "height": "25cm",
      "width": "10cm"
    },
    "warranty": "2 years"
  }
}

### Create Product 2
// @no-log
POST http://localhost:9962/product/
Content-Type: application/json

{
  "id": "p2",
  "name": "EverCharge Portable Battery",
  "readyForMarket": true,
  "released": "2025-02-03",
  "thumbnail": "ZXZlcmNoYXJnZV90aHVtYg==",
  "image": "ZXZlcmNoYXJnZV9pbWFnZQ==",
  "quantity": 1200,
  "desiredSaleQuantity": 8000,
  "price": 49.5,
  "taxRate": 0.06,
  "realTaxRate": 60000000000000000,
  "metadata": {
    "category": "Electronics",
    "capacity_mAh": 20000,
    "ports": [
      "USB-C",
      "Lightning",
      "USB-A"
    ],
    "warranty": "18 months"
  }
}

### Create Product 3
// @no-log
POST http://localhost:9962/product/
Content-Type: application/json

{
  "id": "p3",
  "name": "Nimbus Noise Cancelling Headphones",
  "readyForMarket": false,
  "released": "2025-07-19",
  "thumbnail": "bmltYnVzX3RodW1ibmFpbA==",
  "image": "bmltYnVzX2ltYWdl",
  "quantity": 50,
  "desiredSaleQuantity": 10000,
  "price": 199.99,
  "taxRate": 0.09,
  "realTaxRate": 90000000000000000,
  "metadata": {
    "category": "Audio",
    "wireless": true,
    "batteryLifeHours": 30,
    "materials": [
      "Aluminum",
      "Leatherette"
    ],
    "colorOptions": [
      "Silver",
      "Space Gray"
    ]
  }
}
